spring.application.name=StudentManagmentSystem

spring.datasource.url=jdbc:postgresql://dpg-d7it4gd8nd3s738mh9c0-a.oregon-postgres.render.com:5432/student_db_834m
spring.datasource.username=student_db_834m_user
spring.datasource.password=YNwhYp68gccXVS7ZZy4Re2Zut8AuzTz8

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
